global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cybersim-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway-service:8080
          - identity-service:8080
          - target-registry-service:8080
          - policy-engine-service:8080
          - target-system-service:8080
          - simulation-orchestrator-service:8080
          - vulnerability-registry-service:8080
          - dashboard-backend-service:8080
